/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary": "#3e2400",
        "on-primary-container": "#90a8ff",
        "secondary-container": "#6cf8bb",
        "primary-fixed-dim": "#b6c4ff",
        "error": "#ba1a1a",
        "surface-dim": "#cfdaf2",
        "secondary": "#006c49",
        "surface-container-lowest": "#ffffff",
        "on-background": "#111c2d",
        "inverse-surface": "#263143",
        "surface-container-high": "#dee8ff",
        "slate-gray": "#64748B",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#e7eeff",
        "outline-variant": "#c5c5d3",
        "on-surface-variant": "#444651",
        "tertiary-container": "#5c3800",
        "white": "#FFFFFF",
        "on-tertiary-container": "#ef9900",
        "surface-tint": "#4059aa",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-fixed-variant": "#005236",
        "canvas": "#F3F4F6",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "on-primary-fixed": "#00164e",
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f3ff",
        "on-secondary-container": "#00714d",
        "primary": "#00236f",
        "secondary-fixed": "#6ffbbe",
        "surface-container-highest": "#d8e3fb",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-error": "#ffffff",
        "background": "#f9f9ff",
        "inverse-on-surface": "#ecf1ff",
        "on-surface": "#111c2d",
        "outline": "#757682",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "surface-variant": "#d8e3fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "bottom-nav-height": "72px",
        "margin-mobile": "1rem",
        "container-max": "1280px",
        "sidebar-width": "240px",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "topbar-height": "64px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "ethiopic-body": ["Noto Sans Ethiopic"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "ethiopic-label": ["Noto Sans Ethiopic"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "ethiopic-body": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "ethiopic-label": ["14px", {"lineHeight": "22px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
